### PR TITLE
WIP: Pack rebuild and redesign

### PR DESCRIPTION
**Pull request by namachieli**
This PR represents a redesign of the Palo Alto Integration pack. The most significant change is a migration from pandevice to pan-python.

Related #11 

To Do:
- [x]  Update README - Deprecation Details
- [ ]  Update README - Migration Guide for config, actions, general usage, etc
- [x]  Update CHANGELOG
- [x]  Add warnings to old actions about deprecation and migration
- [ ]  Test that old and new logic operate cleanly side-by-side on st2 3.2 Python 2.7 and 3.6.
- [ ]  Identify current actions that don't have an alternative in the new logic (Unlikely)
- [x]  Add Codeowners files
- [ ]  Stretch goal for this PR: Add unit testing for new logic

### CODE REVIEW

**Comment by namachieli** [comment]
As I work through the checklist of merge items, I would absolutely love feedback about the code itself if anyone is willing/has time. I'm sure there are improvements that could be made. :)

**Comment by nmaludy** [comment]
@namachieli i will try to get you a review sometime this week

**Comment by namachieli** [comment]
Since this has had changes on both sides, I am closing and opening a new PR. (I also already accidentally deleted the source branch 😄  )

**Comment by blag** [comment]
If you deleted it locally then you should be able to pull it from GitHub. If you deleted it from GitHub, then you should be able to restore it from the Branches page of your fork repo.

But we can also close this and have you open a new PR. Whatever is easier.

**Comment by namachieli** [comment]
I deleted it from github, and already opened the new one. Sorry if this is a hassle.

**Pull request closed without merging**
